import os
from dotenv import load_dotenv
from typing import Callable, Dict

# 自动加载.env文件
load_dotenv()

# ✅ 辅助函数：解析 key:value,key:value 格式字符串为字典
def parse_env_dict(env_str: str, value_type: Callable[[str], any] = str) -> Dict[str, any]:
    items = env_str.split(",") if env_str else []
    parsed = {}
    for item in items:
        key, value = item.split(":")
        parsed[key] = value_type(value)
    return parsed


def parse_env_assignment_dict(env_str: str, value_type: Callable[[str], any] = str) -> Dict[str, any]:
    items = env_str.split(",") if env_str else []
    parsed = {}
    for item in items:
        item = item.strip()
        if not item:
            continue
        if "=" in item:
            key, value = item.split("=", 1)
        else:
            key, value = item.rsplit(":", 1)
        parsed[key.strip()] = value_type(value.strip())
    return parsed

# ✅ 辅助函数：解析用逗号分隔的列表
def parse_env_list(env_str):
    if not env_str:
        return []
    return [item.strip() for item in env_str.split(",")]


def parse_env_bool(env_str, default=False):
    if env_str is None:
        return default
    return str(env_str).strip().lower() in {"1", "true", "yes", "on"}

# ✅ OKX API
OKX_API_KEY = os.getenv("OKX_API_KEY")
OKX_SECRET = os.getenv("OKX_SECRET")
OKX_PASSWORD = os.getenv("OKX_PASSWORD")

USE_SERVER = os.getenv("USE_SERVER", '1')
OKX_API_MAX_RETRY = int(os.getenv("OKX_API_MAX_RETRY", 3))
OKX_API_RETRY_SLEEP_SEC = float(os.getenv("OKX_API_RETRY_SLEEP_SEC", 1.0))
OKX_API_RETRY_BACKOFF = float(os.getenv("OKX_API_RETRY_BACKOFF", 1.5))

# ✅ 交易参数
SYMBOL = os.getenv("SYMBOL", "SOL-USDT-SWAP")
LEVERAGE = int(os.getenv("LEVERAGE", 3))
POSITION_SIZE = float(os.getenv("POSITION_SIZE", 50))

# ✅ 多周期
INTERVALS = parse_env_list(os.getenv("INTERVALS", "5m,15m,1H"))
WINDOWS = parse_env_dict(os.getenv("WINDOWS", ""), int)
MA_PERIOD = int(os.getenv("MA_PERIOD", 34))
RSI_PERIOD = int(os.getenv("RSI_PERIOD", 14))

# ✅ 风控参数
TAKE_PROFIT = float(os.getenv("TAKE_PROFIT", 0.028))
STOP_LOSS = float(os.getenv("STOP_LOSS", 0.012))
ADAPTIVE_TP_SL_ENABLED = parse_env_bool(os.getenv("ADAPTIVE_TP_SL_ENABLED"), True)
ATR_TAKE_PROFIT_MULTIPLIER = float(os.getenv("ATR_TAKE_PROFIT_MULTIPLIER", 6.0))
ATR_STOP_LOSS_MULTIPLIER = float(os.getenv("ATR_STOP_LOSS_MULTIPLIER", 2.4))
VOLATILITY_TAKE_PROFIT_MULTIPLIER = float(os.getenv("VOLATILITY_TAKE_PROFIT_MULTIPLIER", 8.0))
VOLATILITY_STOP_LOSS_MULTIPLIER = float(os.getenv("VOLATILITY_STOP_LOSS_MULTIPLIER", 2.8))
ADAPTIVE_TAKE_PROFIT_MIN = float(os.getenv("ADAPTIVE_TAKE_PROFIT_MIN", 0.012))
ADAPTIVE_TAKE_PROFIT_MAX = float(os.getenv("ADAPTIVE_TAKE_PROFIT_MAX", 0.05))
ADAPTIVE_STOP_LOSS_MIN = float(os.getenv("ADAPTIVE_STOP_LOSS_MIN", 0.0065))
ADAPTIVE_STOP_LOSS_MAX = float(os.getenv("ADAPTIVE_STOP_LOSS_MAX", 0.022))
REGIME_HIGH_VOL_STOP_LOSS_MIN = float(os.getenv("REGIME_HIGH_VOL_STOP_LOSS_MIN", ADAPTIVE_STOP_LOSS_MIN))

# ✅ 策略阈值
THRESHOLD_LONG = float(os.getenv("THRESHOLD_LONG", 0.62))
THRESHOLD_SHORT = float(os.getenv("THRESHOLD_SHORT", 0.62))

# ✅ 合约配置
LOT_SIZE = float(os.getenv("LOT_SIZE", 0.01))
TICK_SIZE = float(os.getenv("TICK_SIZE", 0.001))

# ✅ 模型配置
MODEL_PATH = os.getenv("MODEL_PATH", "models/model_okx.pkl")
FEATURE_LIST_PATH = os.getenv("FEATURE_LIST_PATH", "models/feature_list.pkl")
TRAINING_METADATA_PATH = os.getenv("TRAINING_METADATA_PATH", "models/training_metadata.json")
MODEL_PATHS = parse_env_dict(
    os.getenv(
        "MODEL_PATHS",
        "lgb_v1:models/lgb_model.pkl,xgb_v1:models/xgb_model.pkl,rf_v1:models/rf_model.pkl",
    ),
    str,
)
MODEL_WEIGHTS = parse_env_dict(
    os.getenv("MODEL_WEIGHTS", "lgb_v1:0.5,xgb_v1:0.3,rf_v1:0.2"),
    float,
)
MODEL_DIRECTION_MODEL_WEIGHTS = parse_env_assignment_dict(
    os.getenv("MODEL_DIRECTION_MODEL_WEIGHTS", ""),
    str,
)
MODEL_LABEL_FUTURE_WINDOW = int(os.getenv("MODEL_LABEL_FUTURE_WINDOW", 5))
MODEL_LABEL_THRESHOLD = float(os.getenv("MODEL_LABEL_THRESHOLD", 0.002))
MODEL_LABEL_USE_REALISTIC = parse_env_bool(os.getenv("MODEL_LABEL_USE_REALISTIC"), True)
MODEL_LABEL_LOOKAHEAD_BARS = int(os.getenv("MODEL_LABEL_LOOKAHEAD_BARS", 24))
MODEL_LABEL_TAKE_PROFIT = float(os.getenv("MODEL_LABEL_TAKE_PROFIT", 0.016))
MODEL_LABEL_STOP_LOSS = float(os.getenv("MODEL_LABEL_STOP_LOSS", 0.014))
MODEL_LABEL_MIN_NET_RETURN = float(os.getenv("MODEL_LABEL_MIN_NET_RETURN", 0.0))
MODEL_LABEL_MAX_MAE_RATIO = float(os.getenv("MODEL_LABEL_MAX_MAE_RATIO", 1.0))
MODEL_LABEL_TIMEOUT_AS_TRADE = parse_env_bool(os.getenv("MODEL_LABEL_TIMEOUT_AS_TRADE"), True)
MODEL_LABEL_TIMEOUT_WEAK_POSITIVE_AS_TRADE = parse_env_bool(
    os.getenv("MODEL_LABEL_TIMEOUT_WEAK_POSITIVE_AS_TRADE"),
    False,
)
MODEL_LABEL_TIMEOUT_MIN_NET_RETURN = float(os.getenv("MODEL_LABEL_TIMEOUT_MIN_NET_RETURN", 0.0015))
MODEL_LABEL_TIMEOUT_MAX_MAE_RATIO = float(os.getenv("MODEL_LABEL_TIMEOUT_MAX_MAE_RATIO", 0.40))
MODEL_LABEL_LONG_TREND_WEAK_TP_AS_TRADE = parse_env_bool(
    os.getenv("MODEL_LABEL_LONG_TREND_WEAK_TP_AS_TRADE"),
    False,
)
MODEL_LABEL_LONG_TREND_STRONG_MAX_EXIT_BARS = int(os.getenv("MODEL_LABEL_LONG_TREND_STRONG_MAX_EXIT_BARS", 16))
MODEL_LABEL_LONG_TREND_STRONG_MAX_MAE_RATIO = float(os.getenv("MODEL_LABEL_LONG_TREND_STRONG_MAX_MAE_RATIO", 0.50))
MODEL_LABEL_LONG_TREND_STRONG_MIN_MFE_MAE_RATIO = float(os.getenv("MODEL_LABEL_LONG_TREND_STRONG_MIN_MFE_MAE_RATIO", 0.0))
MODEL_LABEL_REQUIRE_REGIME_ALLOWED = parse_env_bool(os.getenv("MODEL_LABEL_REQUIRE_REGIME_ALLOWED"), True)
MODEL_TRAIN_TRADABLE_LABELS = parse_env_bool(os.getenv("MODEL_TRAIN_TRADABLE_LABELS"), True)
MODEL_TRAIN_NO_TRADE_LABELS = parse_env_bool(os.getenv("MODEL_TRAIN_NO_TRADE_LABELS"), True)
MODEL_TRAIN_DIRECTION_QUALITY_MODELS = parse_env_bool(os.getenv("MODEL_TRAIN_DIRECTION_QUALITY_MODELS"), True)
MODEL_DIRECTION_QUALITY_MIN_ROWS = int(os.getenv("MODEL_DIRECTION_QUALITY_MIN_ROWS", 200))
MODEL_DIRECTION_QUALITY_MIN_TRADE_ROWS = int(os.getenv("MODEL_DIRECTION_QUALITY_MIN_TRADE_ROWS", 20))
MODEL_DIRECTION_QUALITY_CALIBRATION = os.getenv("MODEL_DIRECTION_QUALITY_CALIBRATION", "sigmoid")
MODEL_DIRECTION_QUALITY_CALIBRATION_RATIO = float(os.getenv("MODEL_DIRECTION_QUALITY_CALIBRATION_RATIO", 0.20))
MODEL_DIRECTION_QUALITY_CALIBRATION_MIN_ROWS = int(os.getenv("MODEL_DIRECTION_QUALITY_CALIBRATION_MIN_ROWS", 50))
MODEL_DIRECTION_QUALITY_CALIBRATION_MIN_POSITIVES = int(os.getenv("MODEL_DIRECTION_QUALITY_CALIBRATION_MIN_POSITIVES", 5))
MODEL_DIRECTION_QUALITY_CALIBRATION_MIN_NEGATIVES = int(os.getenv("MODEL_DIRECTION_QUALITY_CALIBRATION_MIN_NEGATIVES", 5))
MODEL_DIRECTION_QUALITY_CALIBRATION_USE_SAMPLE_WEIGHT = parse_env_bool(os.getenv("MODEL_DIRECTION_QUALITY_CALIBRATION_USE_SAMPLE_WEIGHT"), False)
MODEL_DIRECTION_QUALITY_ALLOW_INVERSE_CALIBRATION = parse_env_bool(
    os.getenv("MODEL_DIRECTION_QUALITY_ALLOW_INVERSE_CALIBRATION"),
    True,
)
MODEL_DIRECTION_QUALITY_INVERSE_CALIBRATION_DIRECTIONS = parse_env_list(
    os.getenv("MODEL_DIRECTION_QUALITY_INVERSE_CALIBRATION_DIRECTIONS", "short")
)
MODEL_DIRECTION_QUALITY_REGIME_CALIBRATION = parse_env_bool(os.getenv("MODEL_DIRECTION_QUALITY_REGIME_CALIBRATION"), True)
MODEL_DIRECTION_QUALITY_REGIME_CALIBRATION_MIN_ROWS = int(os.getenv("MODEL_DIRECTION_QUALITY_REGIME_CALIBRATION_MIN_ROWS", 50))
MODEL_DIRECTION_QUALITY_REGIME_CALIBRATION_MIN_POSITIVES = int(os.getenv("MODEL_DIRECTION_QUALITY_REGIME_CALIBRATION_MIN_POSITIVES", 5))
MODEL_DIRECTION_QUALITY_REGIME_CALIBRATION_MIN_NEGATIVES = int(os.getenv("MODEL_DIRECTION_QUALITY_REGIME_CALIBRATION_MIN_NEGATIVES", 5))
MODEL_QUALITY_PROBABILITY_EXECUTION_SCALE_ENABLED = parse_env_bool(
    os.getenv("MODEL_QUALITY_PROBABILITY_EXECUTION_SCALE_ENABLED"),
    True,
)
MODEL_QUALITY_PROBABILITY_EXECUTION_ANCHOR = float(os.getenv("MODEL_QUALITY_PROBABILITY_EXECUTION_ANCHOR", 0.50))
MODEL_QUALITY_PROBABILITY_EXECUTION_TEMPERATURE = float(os.getenv("MODEL_QUALITY_PROBABILITY_EXECUTION_TEMPERATURE", 1.0))
MODEL_QUALITY_PROBABILITY_BASE_RATE = float(os.getenv("MODEL_QUALITY_PROBABILITY_BASE_RATE", 0.0))
MODEL_QUALITY_PROBABILITY_MIN_BASE_RATE = float(os.getenv("MODEL_QUALITY_PROBABILITY_MIN_BASE_RATE", 0.01))
MODEL_QUALITY_PROBABILITY_MAX_BASE_RATE = float(os.getenv("MODEL_QUALITY_PROBABILITY_MAX_BASE_RATE", 0.50))
# 是否接入 Rubik(OI/taker/多空比)平稳特征。默认关闭,用 OOS 对比确认有效后再开。
MODEL_USE_RUBIK_FEATURES = parse_env_bool(os.getenv("MODEL_USE_RUBIK_FEATURES"), False)
# Rubik 统计粒度;5m 历史仅~2天不可用,1H 可回溯~30天。
MODEL_RUBIK_PERIOD = os.getenv("MODEL_RUBIK_PERIOD", "1H")
MODEL_RECENT_SAMPLE_WEIGHT_BOOST = float(os.getenv("MODEL_RECENT_SAMPLE_WEIGHT_BOOST", 0.5))
MODEL_TRADE_SAMPLE_WEIGHT_MULTIPLIER = float(os.getenv("MODEL_TRADE_SAMPLE_WEIGHT_MULTIPLIER", 1.0))
MODEL_NO_TRADE_SAMPLE_WEIGHT_MULTIPLIER = float(os.getenv("MODEL_NO_TRADE_SAMPLE_WEIGHT_MULTIPLIER", 1.0))
MODEL_HARD_NEGATIVE_SAMPLE_WEIGHT_MULTIPLIER = float(os.getenv("MODEL_HARD_NEGATIVE_SAMPLE_WEIGHT_MULTIPLIER", 3.0))
MODEL_DIRECTION_TRADE_SAMPLE_WEIGHT_MULTIPLIERS = parse_env_assignment_dict(
    os.getenv("MODEL_DIRECTION_TRADE_SAMPLE_WEIGHT_MULTIPLIERS", ""),
    float,
)
MODEL_DIRECTION_HARD_NEGATIVE_SAMPLE_WEIGHT_MULTIPLIERS = parse_env_assignment_dict(
    os.getenv("MODEL_DIRECTION_HARD_NEGATIVE_SAMPLE_WEIGHT_MULTIPLIERS", "long:trend_long=2.0,short:trend_short=2.0"),
    float,
)
MODEL_SAMPLE_WEIGHT_MIN = float(os.getenv("MODEL_SAMPLE_WEIGHT_MIN", 0.25))
MODEL_SAMPLE_WEIGHT_MAX = float(os.getenv("MODEL_SAMPLE_WEIGHT_MAX", 20.0))
MODEL_TRAIN_RATIO = float(os.getenv("MODEL_TRAIN_RATIO", 0.70))
MODEL_VALIDATION_RATIO = float(os.getenv("MODEL_VALIDATION_RATIO", 0.15))
_DEFAULT_MODEL_PURGE_BARS = max(
    MODEL_LABEL_FUTURE_WINDOW,
    MODEL_LABEL_LOOKAHEAD_BARS if MODEL_LABEL_USE_REALISTIC else MODEL_LABEL_FUTURE_WINDOW,
)
MODEL_PURGE_BARS = int(os.getenv("MODEL_PURGE_BARS", _DEFAULT_MODEL_PURGE_BARS))
MODEL_FINAL_TRAIN_ON_VALIDATION = parse_env_bool(os.getenv("MODEL_FINAL_TRAIN_ON_VALIDATION"), True)
MODEL_TRAIN_LGB_ESTIMATORS = int(os.getenv("MODEL_TRAIN_LGB_ESTIMATORS", 160))
MODEL_TRAIN_XGB_ESTIMATORS = int(os.getenv("MODEL_TRAIN_XGB_ESTIMATORS", 160))
MODEL_TRAIN_RF_ESTIMATORS = int(os.getenv("MODEL_TRAIN_RF_ESTIMATORS", 100))
MODEL_VALIDATION_LIGHTWEIGHT_TRAINING = parse_env_bool(os.getenv("MODEL_VALIDATION_LIGHTWEIGHT_TRAINING"), True)
MODEL_VALIDATION_LGB_ESTIMATORS = int(os.getenv("MODEL_VALIDATION_LGB_ESTIMATORS", 40))
MODEL_VALIDATION_XGB_ESTIMATORS = int(os.getenv("MODEL_VALIDATION_XGB_ESTIMATORS", 40))
MODEL_VALIDATION_RF_ESTIMATORS = int(os.getenv("MODEL_VALIDATION_RF_ESTIMATORS", 30))
MODEL_WALK_FORWARD_ENABLED = parse_env_bool(os.getenv("MODEL_WALK_FORWARD_ENABLED"), True)
MODEL_WALK_FORWARD_FOLDS = int(os.getenv("MODEL_WALK_FORWARD_FOLDS", 3))
MODEL_WALK_FORWARD_MIN_FOLDS = int(os.getenv("MODEL_WALK_FORWARD_MIN_FOLDS", 2))
MODEL_WALK_FORWARD_MIN_VALIDATION_ROWS = int(os.getenv("MODEL_WALK_FORWARD_MIN_VALIDATION_ROWS", 100))
MODEL_WALK_FORWARD_DIAGNOSTIC_THRESHOLD = float(os.getenv("MODEL_WALK_FORWARD_DIAGNOSTIC_THRESHOLD", 0.35))
MODEL_RETRAIN_VALIDATION_GATE_THRESHOLD = os.getenv("MODEL_RETRAIN_VALIDATION_GATE_THRESHOLD", "auto")
MODEL_RETRAIN_VALIDATION_GATE_THRESHOLD_SWEEP = os.getenv(
    "MODEL_RETRAIN_VALIDATION_GATE_THRESHOLD_SWEEP",
    "0.50,0.56,0.60,0.64,0.68,0.72,0.76,0.80",
)
MODEL_RETRAIN_VALIDATION_GATE_TARGET_PRECISION = float(os.getenv("MODEL_RETRAIN_VALIDATION_GATE_TARGET_PRECISION", 0.25))
MODEL_WALK_FORWARD_FAIL_FAST = parse_env_bool(os.getenv("MODEL_WALK_FORWARD_FAIL_FAST"), True)
MODEL_WALK_FORWARD_LIGHTWEIGHT_TRAINING = parse_env_bool(os.getenv("MODEL_WALK_FORWARD_LIGHTWEIGHT_TRAINING"), True)
MODEL_WALK_FORWARD_LGB_ESTIMATORS = int(os.getenv("MODEL_WALK_FORWARD_LGB_ESTIMATORS", 40))
MODEL_WALK_FORWARD_XGB_ESTIMATORS = int(os.getenv("MODEL_WALK_FORWARD_XGB_ESTIMATORS", 40))
MODEL_WALK_FORWARD_RF_ESTIMATORS = int(os.getenv("MODEL_WALK_FORWARD_RF_ESTIMATORS", 30))
MODEL_WALK_FORWARD_MODEL_DIAGNOSTICS = parse_env_bool(os.getenv("MODEL_WALK_FORWARD_MODEL_DIAGNOSTICS"), False)
MODEL_WALK_FORWARD_THRESHOLD_SWEEP_ENABLED = parse_env_bool(os.getenv("MODEL_WALK_FORWARD_THRESHOLD_SWEEP_ENABLED"), True)
MODEL_WALK_FORWARD_THRESHOLD_SWEEP_THRESHOLDS = os.getenv(
    "MODEL_WALK_FORWARD_THRESHOLD_SWEEP_THRESHOLDS",
    "0.12,0.20,0.30,0.40,0.50",
)
MODEL_WALK_FORWARD_THRESHOLD_SWEEP_GAPS = os.getenv(
    "MODEL_WALK_FORWARD_THRESHOLD_SWEEP_GAPS",
    "0.00,0.08,0.12",
)
MODEL_WALK_FORWARD_THRESHOLD_SWEEP_MIN_TARGET_RATIOS = os.getenv(
    "MODEL_WALK_FORWARD_THRESHOLD_SWEEP_MIN_TARGET_RATIOS",
    "0.005,0.010",
)
MODEL_WALK_FORWARD_THRESHOLD_SWEEP_POSITION_CENTERS = os.getenv(
    "MODEL_WALK_FORWARD_THRESHOLD_SWEEP_POSITION_CENTERS",
    "0.05,0.10,0.20,0.30",
)
MODEL_WALK_FORWARD_THRESHOLD_SWEEP_MAX_CANDIDATES = int(os.getenv("MODEL_WALK_FORWARD_THRESHOLD_SWEEP_MAX_CANDIDATES", 48))
MODEL_WALK_FORWARD_THRESHOLD_SWEEP_TOP_N = int(os.getenv("MODEL_WALK_FORWARD_THRESHOLD_SWEEP_TOP_N", 5))
MODEL_WALK_FORWARD_THRESHOLD_SWEEP_EARLY_STOP_ENABLED = parse_env_bool(
    os.getenv("MODEL_WALK_FORWARD_THRESHOLD_SWEEP_EARLY_STOP_ENABLED"),
    True,
)
MODEL_WALK_FORWARD_THRESHOLD_SWEEP_EARLY_STOP_PATIENCE = int(os.getenv(
    "MODEL_WALK_FORWARD_THRESHOLD_SWEEP_EARLY_STOP_PATIENCE",
    16,
))
MODEL_WALK_FORWARD_THRESHOLD_SWEEP_EARLY_STOP_MIN_CLOSED_TRADES = int(os.getenv(
    "MODEL_WALK_FORWARD_THRESHOLD_SWEEP_EARLY_STOP_MIN_CLOSED_TRADES",
    1,
))
MODEL_WALK_FORWARD_THRESHOLD_SWEEP_EARLY_STOP_MIN_PROFIT_FACTOR = float(os.getenv(
    "MODEL_WALK_FORWARD_THRESHOLD_SWEEP_EARLY_STOP_MIN_PROFIT_FACTOR",
    1.05,
))

# ✅ 信号平滑参数
SMOOTH_ALPHA = float(os.getenv("SMOOTH_ALPHA", 0.3))


TRAILING_STOP = float(os.getenv("TRAILING_STOP", 0.03))           # 移动止损 3%
MAX_HOLD_BARS = float(os.getenv("MAX_HOLD_BARS", 96))

MIN_HOLD_BARS=float(os.getenv("MIN_HOLD_BARS", 8))
TRAILING_EXIT=float(os.getenv("TRAILING_EXIT", 0.008))

# ✅ 仓位边界
POSITION_MIN = float(os.getenv("POSITION_MIN", 0.08))
POSITION_MAX = float(os.getenv("POSITION_MAX", 0.45))
POSITION_PROBABILITY_CENTER = float(os.getenv("POSITION_PROBABILITY_CENTER", 0.45))
MAX_POSITION_RATIO = float(os.getenv("MAX_POSITION_RATIO", 0.45))
BASE_POSITION_RATIO = float(os.getenv("BASE_POSITION_RATIO", 0.12))
DYNAMIC_POSITION_MAX = float(os.getenv("DYNAMIC_POSITION_MAX", MAX_POSITION_RATIO))
DYNAMIC_RISK_ENABLED = parse_env_bool(os.getenv("DYNAMIC_RISK_ENABLED"), False)
DYNAMIC_LEVERAGE_MIN = int(os.getenv("DYNAMIC_LEVERAGE_MIN", 1))
DYNAMIC_LEVERAGE_MAX = int(os.getenv("DYNAMIC_LEVERAGE_MAX", LEVERAGE))
DYNAMIC_RISK_HIGH_VOL_MULTIPLIER = float(os.getenv("DYNAMIC_RISK_HIGH_VOL_MULTIPLIER", 0.65))
DYNAMIC_RISK_LOW_SIGNAL_MULTIPLIER = float(os.getenv("DYNAMIC_RISK_LOW_SIGNAL_MULTIPLIER", 0.60))
DYNAMIC_RISK_TREND_MISMATCH_MULTIPLIER = float(os.getenv("DYNAMIC_RISK_TREND_MISMATCH_MULTIPLIER", 0.50))
DYNAMIC_RISK_STRONG_SIGNAL_THRESHOLD = float(os.getenv("DYNAMIC_RISK_STRONG_SIGNAL_THRESHOLD", 0.30))
DYNAMIC_RISK_WEAK_SIGNAL_THRESHOLD = float(os.getenv("DYNAMIC_RISK_WEAK_SIGNAL_THRESHOLD", 0.16))
MIN_ADJUST_AMOUNT = float(os.getenv("MIN_ADJUST_AMOUNT", 75))
ADJUST_UNIT = float(os.getenv("ADJUST_UNIT", 75))
ADD_THRESHOLD = float(os.getenv("ADD_THRESHOLD", 0.25))
MAX_REBALANCE_RATIO = float(os.getenv("MAX_REBALANCE_RATIO", 0.25))
BLOCK_LOSING_POSITION_ADDS = parse_env_bool(os.getenv("BLOCK_LOSING_POSITION_ADDS"), True)
SIGNAL_MIN_PROB_DIFF = float(os.getenv("SIGNAL_MIN_PROB_DIFF", 0.20))
MIN_SIGNAL_TARGET_RATIO = float(os.getenv("MIN_SIGNAL_TARGET_RATIO", 0.08))
REGIME_RANGE_MIN_SIGNAL_TARGET_RATIO = float(os.getenv("REGIME_RANGE_MIN_SIGNAL_TARGET_RATIO", MIN_SIGNAL_TARGET_RATIO))
REGIME_HIGH_VOL_MIN_SIGNAL_TARGET_RATIO = float(os.getenv("REGIME_HIGH_VOL_MIN_SIGNAL_TARGET_RATIO", MIN_SIGNAL_TARGET_RATIO))
REVERSE_SIGNAL_MIN_PROB_DIFF = float(os.getenv("REVERSE_SIGNAL_MIN_PROB_DIFF", 0.28))
REVERSE_MIN_TARGET_RATIO = float(os.getenv("REVERSE_MIN_TARGET_RATIO", 0.12))
REVERSE_EXIT_CONSECUTIVE_BARS = int(os.getenv("REVERSE_EXIT_CONSECUTIVE_BARS", 2))
REVERSE_EXIT_MIN_PROB_DIFF = float(os.getenv("REVERSE_EXIT_MIN_PROB_DIFF", REVERSE_SIGNAL_MIN_PROB_DIFF))

# ✅ 高周期趋势过滤
TREND_FILTER_ENABLED = parse_env_bool(os.getenv("TREND_FILTER_ENABLED"), True)
TREND_FILTER_INTERVAL = os.getenv("TREND_FILTER_INTERVAL", "15m")
TREND_FILTER_FAST_COL = os.getenv("TREND_FILTER_FAST_COL", "ema_20")
TREND_FILTER_SLOW_COL = os.getenv("TREND_FILTER_SLOW_COL", "ema_60")
TREND_FILTER_MIN_GAP = float(os.getenv("TREND_FILTER_MIN_GAP", 0.003))

# ✅ 简单规则模式 - 绕过ML模型,只用trend决定方向
USE_SIMPLE_RULE_MODE = parse_env_bool(os.getenv("USE_SIMPLE_RULE_MODE"), False)
SIMPLE_RULE_POSITION_SIZE = float(os.getenv("SIMPLE_RULE_POSITION_SIZE", 0.15))  # 15% 仓位

# ✅ Regime 分层过滤（先用同一模型，按行情状态调整阈值/仓位/方向）
REGIME_FILTER_ENABLED = parse_env_bool(os.getenv("REGIME_FILTER_ENABLED"), True)
REGIME_TREND_GAP_THRESHOLD = float(os.getenv("REGIME_TREND_GAP_THRESHOLD", TREND_FILTER_MIN_GAP))
REGIME_HIGH_VOL_ATR_THRESHOLD = float(os.getenv("REGIME_HIGH_VOL_ATR_THRESHOLD", 0.0016))
REGIME_HIGH_VOLATILITY_THRESHOLD = float(os.getenv("REGIME_HIGH_VOLATILITY_THRESHOLD", 0.0012))
REGIME_MONEY_FLOW_EXTREME_THRESHOLD = float(os.getenv("REGIME_MONEY_FLOW_EXTREME_THRESHOLD", 1.8))
REGIME_RANGE_ALLOW_TRADES = parse_env_bool(os.getenv("REGIME_RANGE_ALLOW_TRADES"), True)
REGIME_HIGH_VOL_ALLOW_TRADES = parse_env_bool(os.getenv("REGIME_HIGH_VOL_ALLOW_TRADES"), False)
REGIME_RANGE_THRESHOLD_BONUS = float(os.getenv("REGIME_RANGE_THRESHOLD_BONUS", 0.04))
REGIME_HIGH_VOL_THRESHOLD_BONUS = float(os.getenv("REGIME_HIGH_VOL_THRESHOLD_BONUS", 0.06))
REGIME_TREND_AGAINST_BLOCK = parse_env_bool(os.getenv("REGIME_TREND_AGAINST_BLOCK"), True)
REGIME_RANGE_TARGET_MULTIPLIER = float(os.getenv("REGIME_RANGE_TARGET_MULTIPLIER", 0.60))
REGIME_HIGH_VOL_TARGET_MULTIPLIER = float(os.getenv("REGIME_HIGH_VOL_TARGET_MULTIPLIER", 0.35))

# ✅ 反向过滤风控：由 live_fills 亏损状态诊断驱动，先阻断系统性亏损的市场状态。
LOSS_CONDITION_GUARD_ENABLED = parse_env_bool(os.getenv("LOSS_CONDITION_GUARD_ENABLED"), True)
LOSS_GUARD_BLOCK_NEW_REGIMES = parse_env_list(os.getenv("LOSS_GUARD_BLOCK_NEW_REGIMES", "range_high_vol"))
LOSS_GUARD_BLOCK_DIRECTIONS = parse_env_list(os.getenv("LOSS_GUARD_BLOCK_DIRECTIONS", "short"))
LOSS_GUARD_EXIT_REGIMES = parse_env_list(os.getenv("LOSS_GUARD_EXIT_REGIMES", "range_high_vol"))
LOSS_GUARD_EXIT_MIN_HOLD_BARS = int(os.getenv("LOSS_GUARD_EXIT_MIN_HOLD_BARS", 0))
LOSS_GUARD_EXIT_ONLY_WHEN_UNPROFITABLE = parse_env_bool(os.getenv("LOSS_GUARD_EXIT_ONLY_WHEN_UNPROFITABLE"), False)
LOSS_GUARD_EXIT_MIN_UNREALIZED_LOSS = float(os.getenv("LOSS_GUARD_EXIT_MIN_UNREALIZED_LOSS", 0.003))
LOSS_GUARD_EXIT_CONFIRM_BARS = int(os.getenv("LOSS_GUARD_EXIT_CONFIRM_BARS", 2))

# ✅ 多头入场质量保护：避免 trend_long 快衰减或高波动边缘追多。
LONG_ENTRY_GUARD_ENABLED = parse_env_bool(os.getenv("LONG_ENTRY_GUARD_ENABLED"), True)
LONG_ENTRY_MIN_TREND_GAP = float(os.getenv("LONG_ENTRY_MIN_TREND_GAP", TREND_FILTER_MIN_GAP))
LONG_ENTRY_HIGH_VOL_GAP_BUFFER = float(os.getenv("LONG_ENTRY_HIGH_VOL_GAP_BUFFER", 0.0008))
LONG_ENTRY_HIGH_VOL_MIN_TREND_GAP = float(
    os.getenv(
        "LONG_ENTRY_HIGH_VOL_MIN_TREND_GAP",
        0.0050,
    )
)
LONG_ENTRY_BLOCK_HIGH_VOL = parse_env_bool(os.getenv("LONG_ENTRY_BLOCK_HIGH_VOL"), False)
LONG_ENTRY_OVERHEAT_GUARD_ENABLED = parse_env_bool(os.getenv("LONG_ENTRY_OVERHEAT_GUARD_ENABLED"), True)
LONG_ENTRY_OVERHEAT_MONEY_FLOW_MAX = float(os.getenv("LONG_ENTRY_OVERHEAT_MONEY_FLOW_MAX", 2.5))

# ✅ Kelly 盈亏比
KELLY_REWARD_RISK = float(os.getenv("KELLY_REWARD_RISK", 2.8))

# ✅ 动态风险预算
TARGET_VOL = float(os.getenv("TARGET_VOL", 0.02))

# ✅ 回测参数
MAX_POSITION = float(os.getenv("MAX_POSITION", 0.4))
INITIAL_BALANCE = float(os.getenv("INITIAL_BALANCE", 1000))
BACKTEST_MIN_ADJUST_AMOUNT = float(os.getenv(
    "BACKTEST_MIN_ADJUST_AMOUNT",
    min(MIN_ADJUST_AMOUNT, INITIAL_BALANCE * MIN_SIGNAL_TARGET_RATIO),
))
FEE_RATE = float(os.getenv("FEE_RATE", 0.0005))
BACKTEST_SLIPPAGE_BPS = float(os.getenv("BACKTEST_SLIPPAGE_BPS", 3.0))
ESTIMATED_SLIPPAGE_BPS = float(os.getenv("ESTIMATED_SLIPPAGE_BPS", BACKTEST_SLIPPAGE_BPS))
COST_BUFFER_MULTIPLIER = float(os.getenv("COST_BUFFER_MULTIPLIER", 2.0))
MIN_EXPECTED_NET_EDGE = float(os.getenv("MIN_EXPECTED_NET_EDGE", 0.0))
MIN_TAKE_PROFIT_TO_STOP_LOSS_RATIO = float(os.getenv("MIN_TAKE_PROFIT_TO_STOP_LOSS_RATIO", 2.2))
MIN_TAKE_PROFIT_COST_MULTIPLIER = float(os.getenv("MIN_TAKE_PROFIT_COST_MULTIPLIER", 6.0))
TRADE_COOLDOWN_BARS = int(os.getenv("TRADE_COOLDOWN_BARS", 4))
TAKE_PROFIT_COOLDOWN_BARS = int(os.getenv("TAKE_PROFIT_COOLDOWN_BARS", TRADE_COOLDOWN_BARS))
STOP_LOSS_COOLDOWN_BARS = int(os.getenv("STOP_LOSS_COOLDOWN_BARS", max(TRADE_COOLDOWN_BARS, 36)))
BACKTEST_ENABLE_FUNDING = parse_env_bool(os.getenv("BACKTEST_ENABLE_FUNDING"), True)
BACKTEST_FUNDING_HISTORY_LIMIT = int(os.getenv("BACKTEST_FUNDING_HISTORY_LIMIT", 400))
BACKTEST_INTRABAR_TP_SL = parse_env_bool(os.getenv("BACKTEST_INTRABAR_TP_SL"), False)
BACKTEST_WORST_CASE_TP_SL = parse_env_bool(os.getenv("BACKTEST_WORST_CASE_TP_SL"), True)
BACKTEST_FORCE_CLOSE_ON_END = parse_env_bool(os.getenv("BACKTEST_FORCE_CLOSE_ON_END"), True)

# ✅ 实盘/模拟盘保护
LIVE_REQUIRE_SIMULATED_TRADING = parse_env_bool(os.getenv("LIVE_REQUIRE_SIMULATED_TRADING"), True)
LIVE_AUTO_SET_POSITION_MODE = parse_env_bool(os.getenv("LIVE_AUTO_SET_POSITION_MODE"), True)
LIVE_AUTO_SET_LEVERAGE = parse_env_bool(os.getenv("LIVE_AUTO_SET_LEVERAGE"), True)
LIVE_RECONCILE_PENDING_ORDERS = parse_env_bool(os.getenv("LIVE_RECONCILE_PENDING_ORDERS"), True)
LIVE_PERSIST_LAST_BAR = parse_env_bool(os.getenv("LIVE_PERSIST_LAST_BAR"), True)
LIVE_USE_AVAILABLE_MARGIN_FOR_SIZING = parse_env_bool(os.getenv("LIVE_USE_AVAILABLE_MARGIN_FOR_SIZING"), True)
LIVE_MARGIN_USAGE_RATIO = float(os.getenv("LIVE_MARGIN_USAGE_RATIO", 0.85))
LIVE_MIN_FREE_MARGIN_USDT = float(os.getenv("LIVE_MIN_FREE_MARGIN_USDT", 30))
LIVE_REWARD_RISK_MIN = float(os.getenv("LIVE_REWARD_RISK_MIN", 1.2))

# ✅ 自动模型重训
MODEL_RETRAIN_ENABLED = parse_env_bool(os.getenv("MODEL_RETRAIN_ENABLED"), False)
MODEL_RETRAIN_HOUR = int(os.getenv("MODEL_RETRAIN_HOUR", 3))
MODEL_RETRAIN_MINUTE = int(os.getenv("MODEL_RETRAIN_MINUTE", 10))
MODEL_RETRAIN_INTERVAL_HOURS = float(os.getenv("MODEL_RETRAIN_INTERVAL_HOURS", 24))
MODEL_RETRAIN_VALIDATE_BACKTEST = parse_env_bool(os.getenv("MODEL_RETRAIN_VALIDATE_BACKTEST"), True)
MODEL_RETRAIN_MIN_RETURN_PCT = float(os.getenv("MODEL_RETRAIN_MIN_RETURN_PCT", 0.0))
MODEL_RETRAIN_MAX_DRAWDOWN_PCT = float(os.getenv("MODEL_RETRAIN_MAX_DRAWDOWN_PCT", -5.0))
MODEL_RETRAIN_MIN_CLOSED_TRADES = int(os.getenv("MODEL_RETRAIN_MIN_CLOSED_TRADES", 10))
MODEL_RETRAIN_MIN_WIN_RATE_PCT = float(os.getenv("MODEL_RETRAIN_MIN_WIN_RATE_PCT", 45.0))
MODEL_RETRAIN_MIN_PROFIT_FACTOR = float(os.getenv("MODEL_RETRAIN_MIN_PROFIT_FACTOR", 1.05))
MODEL_RETRAIN_MIN_AVG_WIN_LOSS_RATIO = float(os.getenv("MODEL_RETRAIN_MIN_AVG_WIN_LOSS_RATIO", 0.8))
MODEL_RETRAIN_MIN_NET_PNL_AFTER_COSTS = float(os.getenv("MODEL_RETRAIN_MIN_NET_PNL_AFTER_COSTS", 0.0))
MODEL_RETRAIN_MIN_OOS_ROWS = int(os.getenv("MODEL_RETRAIN_MIN_OOS_ROWS", 100))
MODEL_RETRAIN_VALIDATION_GATE_ENABLED = parse_env_bool(os.getenv("MODEL_RETRAIN_VALIDATION_GATE_ENABLED"), True)
MODEL_RETRAIN_MIN_VALIDATION_TRADE_RECALL = float(os.getenv("MODEL_RETRAIN_MIN_VALIDATION_TRADE_RECALL", 0.01))
MODEL_RETRAIN_MIN_VALIDATION_TRADE_PRECISION = float(os.getenv("MODEL_RETRAIN_MIN_VALIDATION_TRADE_PRECISION", 0.25))
MODEL_RETRAIN_MIN_VALIDATION_PREDICTED_TRADES = int(os.getenv("MODEL_RETRAIN_MIN_VALIDATION_PREDICTED_TRADES", 1))
MODEL_RETRAIN_REGIME_GATE_ENABLED = parse_env_bool(os.getenv("MODEL_RETRAIN_REGIME_GATE_ENABLED"), True)
MODEL_RETRAIN_REGIME_GATE_MIN_ROWS = int(os.getenv("MODEL_RETRAIN_REGIME_GATE_MIN_ROWS", 30))
MODEL_RETRAIN_MAX_TREND_SHORT_LONG_DOMINANCE_PCT = float(os.getenv("MODEL_RETRAIN_MAX_TREND_SHORT_LONG_DOMINANCE_PCT", 80.0))
MODEL_RETRAIN_MAX_TREND_LONG_SHORT_DOMINANCE_PCT = float(os.getenv("MODEL_RETRAIN_MAX_TREND_LONG_SHORT_DOMINANCE_PCT", 80.0))
MODEL_RETRAIN_RESTART_LIVE_MONITOR = parse_env_bool(os.getenv("MODEL_RETRAIN_RESTART_LIVE_MONITOR"), True)
MODEL_RETRAIN_KEEP_BACKUPS = int(os.getenv("MODEL_RETRAIN_KEEP_BACKUPS", 5))

# ✅ Telegram配置
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")
TELEGRAM_ENABLED = parse_env_bool(os.getenv("TELEGRAM_ENABLED"), True)
TELEGRAM_LOOP_ERROR_NOTIFY_THRESHOLD = int(os.getenv("TELEGRAM_LOOP_ERROR_NOTIFY_THRESHOLD", 3))
DAILY_REPORT_HOUR = int(os.getenv("DAILY_REPORT_HOUR", 23))
DAILY_REPORT_MINUTE = int(os.getenv("DAILY_REPORT_MINUTE", 59))


POLL_SEC=os.getenv("POLL_SEC", 10)
