import os
from dotenv import load_dotenv
from typing import Callable, Dict

# 自动加载.env文件
load_dotenv()

# ✅ 辅助函数：解析 key:value,key:value 格式字符串为字典
def parse_env_dict(env_str: str, value_type: Callable[[str], any] = str) -> Dict[str, any]:
    items = env_str.split(",") if env_str else []
    parsed = {}
    for item in items:
        key, value = item.split(":")
        parsed[key] = value_type(value)
    return parsed

# ✅ 辅助函数：解析用逗号分隔的列表
def parse_env_list(env_str):
    if not env_str:
        return []
    return [item.strip() for item in env_str.split(",")]


def parse_env_bool(env_str, default=False):
    if env_str is None:
        return default
    return str(env_str).strip().lower() in {"1", "true", "yes", "on"}

# ✅ OKX API
OKX_API_KEY = os.getenv("OKX_API_KEY")
OKX_SECRET = os.getenv("OKX_SECRET")
OKX_PASSWORD = os.getenv("OKX_PASSWORD")

USE_SERVER = os.getenv("USE_SERVER", '1')
OKX_API_MAX_RETRY = int(os.getenv("OKX_API_MAX_RETRY", 3))
OKX_API_RETRY_SLEEP_SEC = float(os.getenv("OKX_API_RETRY_SLEEP_SEC", 1.0))
OKX_API_RETRY_BACKOFF = float(os.getenv("OKX_API_RETRY_BACKOFF", 1.5))

# ✅ 交易参数
SYMBOL = os.getenv("SYMBOL", "SOL-USDT-SWAP")
LEVERAGE = int(os.getenv("LEVERAGE", 3))
POSITION_SIZE = float(os.getenv("POSITION_SIZE", 50))

# ✅ 多周期
INTERVALS = parse_env_list(os.getenv("INTERVALS", "5m,15m,1H"))
WINDOWS = parse_env_dict(os.getenv("WINDOWS", ""), int)
MA_PERIOD = int(os.getenv("MA_PERIOD", 34))
RSI_PERIOD = int(os.getenv("RSI_PERIOD", 14))

# ✅ 风控参数
TAKE_PROFIT = float(os.getenv("TAKE_PROFIT", 0.028))
STOP_LOSS = float(os.getenv("STOP_LOSS", 0.012))
ADAPTIVE_TP_SL_ENABLED = parse_env_bool(os.getenv("ADAPTIVE_TP_SL_ENABLED"), True)
ATR_TAKE_PROFIT_MULTIPLIER = float(os.getenv("ATR_TAKE_PROFIT_MULTIPLIER", 6.0))
ATR_STOP_LOSS_MULTIPLIER = float(os.getenv("ATR_STOP_LOSS_MULTIPLIER", 2.4))
VOLATILITY_TAKE_PROFIT_MULTIPLIER = float(os.getenv("VOLATILITY_TAKE_PROFIT_MULTIPLIER", 8.0))
VOLATILITY_STOP_LOSS_MULTIPLIER = float(os.getenv("VOLATILITY_STOP_LOSS_MULTIPLIER", 2.8))
ADAPTIVE_TAKE_PROFIT_MIN = float(os.getenv("ADAPTIVE_TAKE_PROFIT_MIN", 0.012))
ADAPTIVE_TAKE_PROFIT_MAX = float(os.getenv("ADAPTIVE_TAKE_PROFIT_MAX", 0.05))
ADAPTIVE_STOP_LOSS_MIN = float(os.getenv("ADAPTIVE_STOP_LOSS_MIN", 0.0065))
ADAPTIVE_STOP_LOSS_MAX = float(os.getenv("ADAPTIVE_STOP_LOSS_MAX", 0.022))
REGIME_HIGH_VOL_STOP_LOSS_MIN = float(os.getenv("REGIME_HIGH_VOL_STOP_LOSS_MIN", ADAPTIVE_STOP_LOSS_MIN))

# ✅ 策略阈值
THRESHOLD_LONG = float(os.getenv("THRESHOLD_LONG", 0.62))
THRESHOLD_SHORT = float(os.getenv("THRESHOLD_SHORT", 0.62))

# ✅ 合约配置
LOT_SIZE = float(os.getenv("LOT_SIZE", 0.01))
TICK_SIZE = float(os.getenv("TICK_SIZE", 0.001))

# ✅ 模型配置
MODEL_PATH = os.getenv("MODEL_PATH", "models/model_okx.pkl")
FEATURE_LIST_PATH = os.getenv("FEATURE_LIST_PATH", "models/feature_list.pkl")
TRAINING_METADATA_PATH = os.getenv("TRAINING_METADATA_PATH", "models/training_metadata.json")
MODEL_PATHS = parse_env_dict(os.getenv("MODEL_PATHS", ""), str)
MODEL_WEIGHTS = parse_env_dict(os.getenv("MODEL_WEIGHTS", ""), float)
MODEL_LABEL_FUTURE_WINDOW = int(os.getenv("MODEL_LABEL_FUTURE_WINDOW", 5))
MODEL_LABEL_THRESHOLD = float(os.getenv("MODEL_LABEL_THRESHOLD", 0.002))
MODEL_TRAIN_TRADABLE_LABELS = parse_env_bool(os.getenv("MODEL_TRAIN_TRADABLE_LABELS"), True)
MODEL_TRAIN_NO_TRADE_LABELS = parse_env_bool(os.getenv("MODEL_TRAIN_NO_TRADE_LABELS"), True)
MODEL_RECENT_SAMPLE_WEIGHT_BOOST = float(os.getenv("MODEL_RECENT_SAMPLE_WEIGHT_BOOST", 0.15))
MODEL_SAMPLE_WEIGHT_MIN = float(os.getenv("MODEL_SAMPLE_WEIGHT_MIN", 0.25))
MODEL_SAMPLE_WEIGHT_MAX = float(os.getenv("MODEL_SAMPLE_WEIGHT_MAX", 5.0))
MODEL_TRAIN_RATIO = float(os.getenv("MODEL_TRAIN_RATIO", 0.70))
MODEL_VALIDATION_RATIO = float(os.getenv("MODEL_VALIDATION_RATIO", 0.15))
MODEL_PURGE_BARS = int(os.getenv("MODEL_PURGE_BARS", MODEL_LABEL_FUTURE_WINDOW))
MODEL_WALK_FORWARD_ENABLED = parse_env_bool(os.getenv("MODEL_WALK_FORWARD_ENABLED"), True)
MODEL_WALK_FORWARD_FOLDS = int(os.getenv("MODEL_WALK_FORWARD_FOLDS", 3))
MODEL_WALK_FORWARD_MIN_FOLDS = int(os.getenv("MODEL_WALK_FORWARD_MIN_FOLDS", 2))
MODEL_WALK_FORWARD_MIN_VALIDATION_ROWS = int(os.getenv("MODEL_WALK_FORWARD_MIN_VALIDATION_ROWS", 100))

# ✅ 信号平滑参数
SMOOTH_ALPHA = float(os.getenv("SMOOTH_ALPHA", 0.3))


TRAILING_STOP = float(os.getenv("TRAILING_STOP", 0.03))           # 移动止损 3%
MAX_HOLD_BARS = float(os.getenv("MAX_HOLD_BARS", 96))

MIN_HOLD_BARS=float(os.getenv("MIN_HOLD_BARS", 8))
TRAILING_EXIT=float(os.getenv("TRAILING_EXIT", 0.008))

# ✅ 仓位边界
POSITION_MIN = float(os.getenv("POSITION_MIN", 0.08))
POSITION_MAX = float(os.getenv("POSITION_MAX", 0.45))
MAX_POSITION_RATIO = float(os.getenv("MAX_POSITION_RATIO", 0.45))
BASE_POSITION_RATIO = float(os.getenv("BASE_POSITION_RATIO", 0.12))
DYNAMIC_POSITION_MAX = float(os.getenv("DYNAMIC_POSITION_MAX", MAX_POSITION_RATIO))
DYNAMIC_RISK_ENABLED = parse_env_bool(os.getenv("DYNAMIC_RISK_ENABLED"), False)
DYNAMIC_LEVERAGE_MIN = int(os.getenv("DYNAMIC_LEVERAGE_MIN", 1))
DYNAMIC_LEVERAGE_MAX = int(os.getenv("DYNAMIC_LEVERAGE_MAX", LEVERAGE))
DYNAMIC_RISK_HIGH_VOL_MULTIPLIER = float(os.getenv("DYNAMIC_RISK_HIGH_VOL_MULTIPLIER", 0.65))
DYNAMIC_RISK_LOW_SIGNAL_MULTIPLIER = float(os.getenv("DYNAMIC_RISK_LOW_SIGNAL_MULTIPLIER", 0.60))
DYNAMIC_RISK_TREND_MISMATCH_MULTIPLIER = float(os.getenv("DYNAMIC_RISK_TREND_MISMATCH_MULTIPLIER", 0.50))
DYNAMIC_RISK_STRONG_SIGNAL_THRESHOLD = float(os.getenv("DYNAMIC_RISK_STRONG_SIGNAL_THRESHOLD", 0.30))
DYNAMIC_RISK_WEAK_SIGNAL_THRESHOLD = float(os.getenv("DYNAMIC_RISK_WEAK_SIGNAL_THRESHOLD", 0.16))
MIN_ADJUST_AMOUNT = float(os.getenv("MIN_ADJUST_AMOUNT", 75))
ADJUST_UNIT = float(os.getenv("ADJUST_UNIT", 75))
ADD_THRESHOLD = float(os.getenv("ADD_THRESHOLD", 0.25))
MAX_REBALANCE_RATIO = float(os.getenv("MAX_REBALANCE_RATIO", 0.25))
BLOCK_LOSING_POSITION_ADDS = parse_env_bool(os.getenv("BLOCK_LOSING_POSITION_ADDS"), True)
SIGNAL_MIN_PROB_DIFF = float(os.getenv("SIGNAL_MIN_PROB_DIFF", 0.20))
MIN_SIGNAL_TARGET_RATIO = float(os.getenv("MIN_SIGNAL_TARGET_RATIO", 0.08))
REGIME_RANGE_MIN_SIGNAL_TARGET_RATIO = float(os.getenv("REGIME_RANGE_MIN_SIGNAL_TARGET_RATIO", MIN_SIGNAL_TARGET_RATIO))
REGIME_HIGH_VOL_MIN_SIGNAL_TARGET_RATIO = float(os.getenv("REGIME_HIGH_VOL_MIN_SIGNAL_TARGET_RATIO", MIN_SIGNAL_TARGET_RATIO))
REVERSE_SIGNAL_MIN_PROB_DIFF = float(os.getenv("REVERSE_SIGNAL_MIN_PROB_DIFF", 0.28))
REVERSE_MIN_TARGET_RATIO = float(os.getenv("REVERSE_MIN_TARGET_RATIO", 0.12))
REVERSE_EXIT_CONSECUTIVE_BARS = int(os.getenv("REVERSE_EXIT_CONSECUTIVE_BARS", 2))
REVERSE_EXIT_MIN_PROB_DIFF = float(os.getenv("REVERSE_EXIT_MIN_PROB_DIFF", REVERSE_SIGNAL_MIN_PROB_DIFF))

# ✅ 高周期趋势过滤
TREND_FILTER_ENABLED = parse_env_bool(os.getenv("TREND_FILTER_ENABLED"), True)
TREND_FILTER_INTERVAL = os.getenv("TREND_FILTER_INTERVAL", "15m")
TREND_FILTER_FAST_COL = os.getenv("TREND_FILTER_FAST_COL", "ema_20")
TREND_FILTER_SLOW_COL = os.getenv("TREND_FILTER_SLOW_COL", "ema_60")
TREND_FILTER_MIN_GAP = float(os.getenv("TREND_FILTER_MIN_GAP", 0.003))

# ✅ Regime 分层过滤（先用同一模型，按行情状态调整阈值/仓位/方向）
REGIME_FILTER_ENABLED = parse_env_bool(os.getenv("REGIME_FILTER_ENABLED"), True)
REGIME_TREND_GAP_THRESHOLD = float(os.getenv("REGIME_TREND_GAP_THRESHOLD", TREND_FILTER_MIN_GAP))
REGIME_HIGH_VOL_ATR_THRESHOLD = float(os.getenv("REGIME_HIGH_VOL_ATR_THRESHOLD", 0.0016))
REGIME_HIGH_VOLATILITY_THRESHOLD = float(os.getenv("REGIME_HIGH_VOLATILITY_THRESHOLD", 0.0012))
REGIME_MONEY_FLOW_EXTREME_THRESHOLD = float(os.getenv("REGIME_MONEY_FLOW_EXTREME_THRESHOLD", 1.8))
REGIME_RANGE_ALLOW_TRADES = parse_env_bool(os.getenv("REGIME_RANGE_ALLOW_TRADES"), True)
REGIME_HIGH_VOL_ALLOW_TRADES = parse_env_bool(os.getenv("REGIME_HIGH_VOL_ALLOW_TRADES"), False)
REGIME_RANGE_THRESHOLD_BONUS = float(os.getenv("REGIME_RANGE_THRESHOLD_BONUS", 0.04))
REGIME_HIGH_VOL_THRESHOLD_BONUS = float(os.getenv("REGIME_HIGH_VOL_THRESHOLD_BONUS", 0.06))
REGIME_TREND_AGAINST_BLOCK = parse_env_bool(os.getenv("REGIME_TREND_AGAINST_BLOCK"), True)
REGIME_RANGE_TARGET_MULTIPLIER = float(os.getenv("REGIME_RANGE_TARGET_MULTIPLIER", 0.60))
REGIME_HIGH_VOL_TARGET_MULTIPLIER = float(os.getenv("REGIME_HIGH_VOL_TARGET_MULTIPLIER", 0.35))

# ✅ Kelly 盈亏比
KELLY_REWARD_RISK = float(os.getenv("KELLY_REWARD_RISK", 2.8))

# ✅ 动态风险预算
TARGET_VOL = float(os.getenv("TARGET_VOL", 0.02))

# ✅ 回测参数
MAX_POSITION = float(os.getenv("MAX_POSITION", 0.4))
INITIAL_BALANCE = float(os.getenv("INITIAL_BALANCE", 1000))
BACKTEST_MIN_ADJUST_AMOUNT = float(os.getenv(
    "BACKTEST_MIN_ADJUST_AMOUNT",
    min(MIN_ADJUST_AMOUNT, INITIAL_BALANCE * MIN_SIGNAL_TARGET_RATIO),
))
FEE_RATE = float(os.getenv("FEE_RATE", 0.0005))
BACKTEST_SLIPPAGE_BPS = float(os.getenv("BACKTEST_SLIPPAGE_BPS", 3.0))
ESTIMATED_SLIPPAGE_BPS = float(os.getenv("ESTIMATED_SLIPPAGE_BPS", BACKTEST_SLIPPAGE_BPS))
COST_BUFFER_MULTIPLIER = float(os.getenv("COST_BUFFER_MULTIPLIER", 2.0))
MIN_EXPECTED_NET_EDGE = float(os.getenv("MIN_EXPECTED_NET_EDGE", 0.0))
MIN_TAKE_PROFIT_TO_STOP_LOSS_RATIO = float(os.getenv("MIN_TAKE_PROFIT_TO_STOP_LOSS_RATIO", 2.2))
MIN_TAKE_PROFIT_COST_MULTIPLIER = float(os.getenv("MIN_TAKE_PROFIT_COST_MULTIPLIER", 6.0))
TRADE_COOLDOWN_BARS = int(os.getenv("TRADE_COOLDOWN_BARS", 4))
TAKE_PROFIT_COOLDOWN_BARS = int(os.getenv("TAKE_PROFIT_COOLDOWN_BARS", TRADE_COOLDOWN_BARS))
STOP_LOSS_COOLDOWN_BARS = int(os.getenv("STOP_LOSS_COOLDOWN_BARS", max(TRADE_COOLDOWN_BARS, 36)))
BACKTEST_ENABLE_FUNDING = parse_env_bool(os.getenv("BACKTEST_ENABLE_FUNDING"), True)
BACKTEST_FUNDING_HISTORY_LIMIT = int(os.getenv("BACKTEST_FUNDING_HISTORY_LIMIT", 400))
BACKTEST_INTRABAR_TP_SL = parse_env_bool(os.getenv("BACKTEST_INTRABAR_TP_SL"), False)
BACKTEST_WORST_CASE_TP_SL = parse_env_bool(os.getenv("BACKTEST_WORST_CASE_TP_SL"), True)

# ✅ 实盘/模拟盘保护
LIVE_REQUIRE_SIMULATED_TRADING = parse_env_bool(os.getenv("LIVE_REQUIRE_SIMULATED_TRADING"), True)
LIVE_AUTO_SET_POSITION_MODE = parse_env_bool(os.getenv("LIVE_AUTO_SET_POSITION_MODE"), True)
LIVE_AUTO_SET_LEVERAGE = parse_env_bool(os.getenv("LIVE_AUTO_SET_LEVERAGE"), True)
LIVE_RECONCILE_PENDING_ORDERS = parse_env_bool(os.getenv("LIVE_RECONCILE_PENDING_ORDERS"), True)
LIVE_PERSIST_LAST_BAR = parse_env_bool(os.getenv("LIVE_PERSIST_LAST_BAR"), True)
LIVE_USE_AVAILABLE_MARGIN_FOR_SIZING = parse_env_bool(os.getenv("LIVE_USE_AVAILABLE_MARGIN_FOR_SIZING"), True)
LIVE_MARGIN_USAGE_RATIO = float(os.getenv("LIVE_MARGIN_USAGE_RATIO", 0.85))
LIVE_MIN_FREE_MARGIN_USDT = float(os.getenv("LIVE_MIN_FREE_MARGIN_USDT", 30))
LIVE_REWARD_RISK_MIN = float(os.getenv("LIVE_REWARD_RISK_MIN", 1.2))

# ✅ 自动模型重训
MODEL_RETRAIN_ENABLED = parse_env_bool(os.getenv("MODEL_RETRAIN_ENABLED"), False)
MODEL_RETRAIN_HOUR = int(os.getenv("MODEL_RETRAIN_HOUR", 3))
MODEL_RETRAIN_MINUTE = int(os.getenv("MODEL_RETRAIN_MINUTE", 10))
MODEL_RETRAIN_INTERVAL_HOURS = float(os.getenv("MODEL_RETRAIN_INTERVAL_HOURS", 24))
MODEL_RETRAIN_VALIDATE_BACKTEST = parse_env_bool(os.getenv("MODEL_RETRAIN_VALIDATE_BACKTEST"), True)
MODEL_RETRAIN_MIN_RETURN_PCT = float(os.getenv("MODEL_RETRAIN_MIN_RETURN_PCT", 0.0))
MODEL_RETRAIN_MAX_DRAWDOWN_PCT = float(os.getenv("MODEL_RETRAIN_MAX_DRAWDOWN_PCT", -5.0))
MODEL_RETRAIN_MIN_CLOSED_TRADES = int(os.getenv("MODEL_RETRAIN_MIN_CLOSED_TRADES", 10))
MODEL_RETRAIN_MIN_WIN_RATE_PCT = float(os.getenv("MODEL_RETRAIN_MIN_WIN_RATE_PCT", 45.0))
MODEL_RETRAIN_MIN_PROFIT_FACTOR = float(os.getenv("MODEL_RETRAIN_MIN_PROFIT_FACTOR", 1.05))
MODEL_RETRAIN_MIN_AVG_WIN_LOSS_RATIO = float(os.getenv("MODEL_RETRAIN_MIN_AVG_WIN_LOSS_RATIO", 0.8))
MODEL_RETRAIN_MIN_NET_PNL_AFTER_COSTS = float(os.getenv("MODEL_RETRAIN_MIN_NET_PNL_AFTER_COSTS", 0.0))
MODEL_RETRAIN_MIN_OOS_ROWS = int(os.getenv("MODEL_RETRAIN_MIN_OOS_ROWS", 100))
MODEL_RETRAIN_REGIME_GATE_ENABLED = parse_env_bool(os.getenv("MODEL_RETRAIN_REGIME_GATE_ENABLED"), True)
MODEL_RETRAIN_REGIME_GATE_MIN_ROWS = int(os.getenv("MODEL_RETRAIN_REGIME_GATE_MIN_ROWS", 30))
MODEL_RETRAIN_MAX_TREND_SHORT_LONG_DOMINANCE_PCT = float(os.getenv("MODEL_RETRAIN_MAX_TREND_SHORT_LONG_DOMINANCE_PCT", 80.0))
MODEL_RETRAIN_MAX_TREND_LONG_SHORT_DOMINANCE_PCT = float(os.getenv("MODEL_RETRAIN_MAX_TREND_LONG_SHORT_DOMINANCE_PCT", 80.0))
MODEL_RETRAIN_RESTART_LIVE_MONITOR = parse_env_bool(os.getenv("MODEL_RETRAIN_RESTART_LIVE_MONITOR"), True)
MODEL_RETRAIN_KEEP_BACKUPS = int(os.getenv("MODEL_RETRAIN_KEEP_BACKUPS", 5))

# ✅ Telegram配置
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")
TELEGRAM_ENABLED = parse_env_bool(os.getenv("TELEGRAM_ENABLED"), True)
TELEGRAM_LOOP_ERROR_NOTIFY_THRESHOLD = int(os.getenv("TELEGRAM_LOOP_ERROR_NOTIFY_THRESHOLD", 3))
DAILY_REPORT_HOUR = int(os.getenv("DAILY_REPORT_HOUR", 23))
DAILY_REPORT_MINUTE = int(os.getenv("DAILY_REPORT_MINUTE", 59))


POLL_SEC=os.getenv("POLL_SEC", 10)
